import { Button, Card, Label, TextInput } from "flowbite-react";
import { useState } from "react";
import { useRouter } from "next/router";
import { usePocketBase } from "../src/hooks/usePocketbase";
import Head from "next/head";

export default function LoginPage() {
  const { client } = usePocketBase();
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const login = async (event: { preventDefault: () => void }) => {
    event.preventDefault();
    client
      .collection("users")
      .authWithPassword(email, password)
      .then((record) => {
        console.log(record);
        router.reload();
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white min-h-screen flex flex-col justify-center items-center dark:bg-gray-900">
        <Card className="max-w-sm">
          <form onSubmit={login} className="flex flex-col gap-4">
            <div>
              <div className="mb-2 block">
                <Label htmlFor="email" value="Email" />
              </div>
              <TextInput
                id="email1"
                type="email"
                placeholder="name@flowbite.com"
                onChange={(event) => setEmail(event.target.value)}
              />
            </div>
            <div>
              <div className="mb-2 block">
                <Label htmlFor="password" value="Passwort" />
              </div>
              <TextInput
                id="password1"
                type="password"
                onChange={(event) => setPassword(event.target.value)}
              />
            </div>
            <Button color="light" type="submit">
              Anmelden
            </Button>
          </form>
        </Card>
      </main>
    </>
  );
}
