import { Timeline, Button, Card } from "flowbite-react";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { usePocketBase } from "../../src/hooks/usePocketbase";

export default function DocumentListPage() {
    const { client } = usePocketBase();
    const [documents, setDocuments] = useState<IDocument[]>();

    interface IUser {
        id?: string;
        created?: string;
        upadted?: string;
        username?: string;
        name?: string;
        avatar?: string;
        email?: string;
        emailVisibility?: boolean;
        verified?: boolean;
      }
    
      interface IDocument {
        id?: string;
        collectionName?: string;
        collectionId?: string;
        created?: string;
        upadted?: string;
        name?: string;
        file?: File;
        users?: IUser[];
        signatures?: ISignature[];
      }
    
      interface ISignature {
        id?: string;
        created?: string;
        upadted?: string;
        user?: IUser;
        file?: string;
      }    

    const getDocuments = async () => {
        try {
          const records = await client.collection("documents").getFullList(200, {
            filter: `users ~ '${client.authStore.model?.id}'`,
            sort: "-created",
            expand: "users,signatures",
          });
          setDocuments(records);
        } catch (error) {
          console.log("Error occurred while fetching data", error);
        }
      };

      useEffect(() => {
        getDocuments()
      })

  return (
    <>
      <Head>
        <title>DocumentListPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Timeline>
        {documents?.map((document, index) => (
          <Timeline.Item key={index}>
            <Card>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time>{document.created}</Timeline.Time>
                <Timeline.Title>{document.name}</Timeline.Title>
                <Timeline.Body></Timeline.Body>
                <Button.Group>
                  <Button href={`http://212.227.165.185/api/files/${document.collectionId}/${document.id}/${document.file}`} color="gray">Herunterladen</Button>
                  <Button href={`/documents/${document.id}`} color="gray">
                  Unterschreiben
                  </Button>       
                </Button.Group>
              </Timeline.Content>
            </Card>
          </Timeline.Item>
        ))}
      </Timeline>
    </>
  );
}
